#! /bin/sh

echo $HOSTNAME | grep linux400513.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 2148 
else 
rsh linux400513.dc.engr.scu.edu kill 2148 
 sleep 10 
rsh linux400513.dc.engr.scu.edu kill -9 2148 
fi
