#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/./TOPCELLNAME_err | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/XNOR_Logic.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/run_details/duse_master.tmp && \
mv /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/run_details/duse_master.tmp /DCNFS/users/student/cmorali/elen153/synopsys_custom/pvjob_Lab4.XNOR_Logic.icv.lvs/run_details/duse_master
