#! /bin/sh

echo $HOSTNAME | grep linux400510.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 22094 
else 
rsh linux400510.dc.engr.scu.edu kill 22094 
 sleep 10 
rsh linux400510.dc.engr.scu.edu kill -9 22094 
fi
