ENVIRONMENT STRING  SAED90_PDK = "/opt/synopsys-2019/app/SAED/SAED_PDK90nm"
EXTRACTION_FLOW   = true
COMPARE_DIR       = run_details/compare
COMPARE_NETLIST_FLOW = ICV
STATUS_COMPARE    = 0
WRITE_EQUIV_NETLISTS = ALL
