#! /bin/sh
total=0
pathsize=`du -s --block-size=1 /DCNFS/users/student/cmorali/elen153/Adder/synopsys_custom/pvjob_Four_bit_Adder.Half_Adder.icv.drc/run_details | awk '{print $1}'`
total=$(($total+$pathsize))
pathsize=`du -s --block-size=1 /DCNFS/users/student/cmorali/elen153/Adder/synopsys_custom/pvjob_Four_bit_Adder.Half_Adder.icv.drc/Half_Adder.LAYOUT_ERRORS | awk '{print $1}'`
total=$(($total+$pathsize))
echo $total > /DCNFS/users/student/cmorali/elen153/Adder/synopsys_custom/pvjob_Four_bit_Adder.Half_Adder.icv.drc/run_details/duse_master.tmp && \
mv /DCNFS/users/student/cmorali/elen153/Adder/synopsys_custom/pvjob_Four_bit_Adder.Half_Adder.icv.drc/run_details/duse_master.tmp /DCNFS/users/student/cmorali/elen153/Adder/synopsys_custom/pvjob_Four_bit_Adder.Half_Adder.icv.drc/run_details/duse_master
