#! /bin/sh

echo $HOSTNAME | grep linux400513.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 18345 
else 
rsh linux400513.dc.engr.scu.edu kill 18345 
 sleep 10 
rsh linux400513.dc.engr.scu.edu kill -9 18345 
fi
