all: lab8part2.c lab8part3.c lab8part4.c lab8part5.c
	gcc -o step2 lab8part2.c
	gcc -o step3 lab8part3.c
	gcc -o step4 lab8part4.c
	gcc -o step5 lab8part5.c -lpthread

clean:
	rm -f *.out step2 step3 step4 step5