gi::showContextMenu [gi::findChild dmLibraryManager -in [gi::getWindows 1]]
gi::hideContextMenu
gi::showContextMenu [gi::findChild dmLibraryManager -in [gi::getWindows 1]]
gi::hideContextMenu
gi::showContextMenu [gi::findChild dmLibraryManager -in [gi::getWindows 1]]
gi::hideContextMenu
gi::showContextMenu [gi::findChild dmLibraryManager -in [gi::getWindows 1]]
gi::hideContextMenu
dm::showLibraryManager
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setCurrentIndex {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
gi::sortItems {libs} -column {Libraries} -order {descending} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {verilogaLib} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {verilogaLib} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {SAED_PDK_90} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {SAED_PDK_90} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {SAED_PDK_90} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {SAED_PDK_90} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Tutorial} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Tutorial} -in [gi::getWindows 2]
gi::executeAction {menuPreShow} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Inverter} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab1} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab2} -in [gi::getWindows 2]
gi::setCurrentIndex {libs} -index {Lab4} -in [gi::getWindows 2]
gi::setItemSelection {cells} -index {4_to_2} -in [gi::getWindows 2]
gi::setItemSelection {libs} -index {Lab4} -in [gi::getWindows 2]
db::setAttr geometry -of [gi::getFrames 1] -value 1040x824+1055+93
db::setAttr geometry -of [gi::getFrames 1] -value 1040x824+465+139
exit
