::sa::_backgroundSaeShell::signalProcessReady 1681166533
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession2 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab1,Voltage_Divider,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::wf::viewerExited
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::exit
