#! /bin/sh

echo $HOSTNAME | grep linux400510.dc.engr.scu.edu > /dev/null 2>&1 
if [ $? == 0  ]
then 
kill 23775 
else 
rsh linux400510.dc.engr.scu.edu kill 23775 
 sleep 10 
rsh linux400510.dc.engr.scu.edu kill -9 23775 
fi
