::sa::_backgroundSaeShell::signalProcessReady 1682979968
::sa::_backgroundSaeShell::parentRunning
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession0 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession0 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession0 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession0 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::runScript /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/.bg_measurement_script.tcl sa::_resultsDatabase::saeShellProcessingCompletedProc testSuiteName saeSession0 testbenchName HSPICE_default resultsDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/results testSuiteDir /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal databaseName /DCNFS/users/student/cmorali/simulation/Lab4,Test_bench,schematic/history_1/simulation/HSPICE_default/HSPICE/nominal/resultsDatabase remoteRun {} testbenchId 1 saveImages true
::sa::_backgroundSaeShell::parentRunning
::wf::viewerExited
::sa::_backgroundSaeShell::exit
